### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by jwjordan** [RecastAI/bot-slack#1]
Not sure if this is something you can help with, but I am on Ubuntu 14.04 running version 6.8.1 of node and 3.10.8 of npm.  I can run "sudo npm run start" without any trouble, until I type any word into the Slack channel where the chat bot I created and connected lives.  When I do that, I get the following:

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @1.0.0 start: `node ./node_modules/babel-cli/bin/babel-node.js src/bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.0 start script 'node ./node_modules/babel-cli/bin/babel-node.js src/bot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/babel-cli/bin/babel-node.js src/bot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

I have no idea where to go from here, since I think I am running the latest versions of node and npm.

**Comment by ftriquet** [comment]
Hi @jwjordan, is there any other error message above the one that you pasted ?

**Comment by jwjordan** [comment]
No, when I run "sudo npm run start" in a shell, it runs until a word is typed in the Slack channel, and that error message appears.  The nodejs log doesn't show anything different either.

**Comment by ftriquet** [comment]
Ok, can you try to set the logLevel parameter in bot.js to 'error' instead of 'false' and run it again to see if there are additional error messages from slack ?

**Comment by jwjordan** [comment]
Yes, more info!  Though, I still don't get the problem:

> @1.0.0 start /home/ubuntu/github/bot-slack
> node ./node_modules/babel-cli/bin/babel-node.js src/bot.js

/home/ubuntu/github/bot-slack/src/bot.js:20
  var dm = rtm.dataStore.getDMByName(user.name).id;
                                               ^

TypeError: Cannot read property 'id' of undefined
    at RTMClient.<anonymous> (/home/ubuntu/github/bot-slack/src/bot.js:18:14)
    at RTMClient.emit (/home/ubuntu/github/bot-slack/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/home/ubuntu/github/bot-slack/node_modules/@slack/client/lib/clients/client.js:83:39)
    at RTMClient._handleWsMessageViaEventHandler (/home/ubuntu/github/bot-slack/node_modules/@slack/client/lib/clients/rtm/client.js:466:10)
    at RTMClient.handleWsMessage (/home/ubuntu/github/bot-slack/node_modules/@slack/client/lib/clients/rtm/client.js:420:10)
    at WebSocket.wrapper (/home/ubuntu/github/bot-slack/node_modules/lodash/lodash.js:4941:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/ubuntu/github/bot-slack/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/ubuntu/github/bot-slack/node_modules/ws/lib/Receiver.js:536:18
    at /home/ubuntu/github/bot-slack/node_modules/ws/lib/Receiver.js:368:7
    at /home/ubuntu/github/bot-slack/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:387:3)
    at onwrite (_stream_writable.js:378:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)

**Comment by ftriquet** [comment]
Hm ok. Do you talk to your bot by direct message or in a channel?

**Comment by jwjordan** [comment]
OK, that was the problem.  I was trying to talk to the bot in a channel, without using the @bot notation.  It seems that the crash only happens when a message is sent in the channel but *not* directed at the bot.  If I use @bot or if I chat directly with the bot in a direct message, everything works as expected.  Thanks for helping me narrow this down and get it working!

**Comment by ftriquet** [comment]
Ok nice, maybe you can try to replace
```const dm = rtm.dataStore.getDMByName(user.name).id```
by
```const dm = message.channel```

This will allow your bot to reply in the channel where you talked.

Cheers
